#!/bin/bash

export PGPASSWORD=$origpass

if [ "$docopy" = "c" ]; then 
  echo Copy $orighost':'$origdb to $checkhost':'$checkdb 1>&2
else
  echo Do Update $orighost':'$origdb to $checkhost':'$checkdb 1>&2
fi
schema='mne_application'
schemasave=$schema""_save

echo "Save custumized Data" 1>&2
. do_contentsave > content.sql

if [ "$docopy" != "c" ]; then
   echo "Rewrite custumized Data" 1>&2
   schema='mne_application'
   schemasave=$schema""_save
  . do_contentcopy >> content.sql
fi

